services:
  db:
    image: postgres:15
    container_name: mollidays-db
    env_file:
      - ./backend/.env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6.0
    container_name: mollidays-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build:
      context: ./backend
    container_name: mollidays-backend
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python scripts/seed_all.py &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: mollidays-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  pgdata:
  mongodata:
